version: "3"
services: 
    nginx:
        ports: 
            - "80:80"
    node-app:
        build:
            context: .
            args: 
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            - SESSION_SECRET=${SESSION_SECRET}
        command: node index.js
    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}


# to save variable on ubuntu: export SESSION_SECRET="HELLO", THEN RUN PRINT ENV
# set -o allexport; source /root/.env; set +o allexport